[package]
name = "flat_engine"
version = "0.1.0"
authors = ["admin <merlotec@gmail.com>"]

[dependencies]
gfx = "0.17.1"
glutin = "0.18.0"
gfx_window_glutin = "0.26.0"
gfx_device_gl = "0.15.3"
image = "0.20.0"
rusttype = "0.7.2"
time = "0.1.*"
cgmath = "0.14.*"
stopwatch = "0.0.7"